import pyautogui, time, pydirectinput


def main():
    pyautogui.FAILSAFE = True

    print("Starting", end="")
    for i in range(0, 1):
        print(".")
        time.sleep(1)
    print("Go")

    pyautogui.dragTo(515, 1054, 1)
    pyautogui.leftClick()
    pyautogui.dragTo(324, 68, 1)
    pyautogui.leftClick()
    pyautogui.typewrite('https://www.roblox.com/games/8842647523/Python-Bot')
    pyautogui.press('enter')
    pyautogui.dragTo(538, 838, 1)
    pyautogui.leftClick()
    time.sleep(10)

    pydirectinput.press('/')
    pydirectinput.typewrite('/e wave')
    pydirectinput.press('enter')
    pydirectinput.press('/')
    pydirectinput.typewrite(" hello, this is all automated.")
    pydirectinput.press('enter')

    pydirectinput.keyDown('d')
    time.sleep(6.6)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('s')
    time.sleep(0.7)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('a')
    time.sleep(3.5)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(0.4)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('d')
    time.sleep(8.5)
    pydirectinput.keyUp('d')
    print("input")
    pydirectinput.keyDown('d')
    pydirectinput.press(' ')
    time.sleep(0.3)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown(' ')
    pydirectinput.keyDown('d')
    time.sleep(0.3)
    pydirectinput.keyUp(' ')
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('d')
    pydirectinput.keyDown(' ')
    time.sleep(0.3)
    pydirectinput.keyUp(' ')
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('d')
    pydirectinput.keyDown(' ')
    time.sleep(0.3)
    pydirectinput.keyUp(' ')
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('d')
    pydirectinput.keyDown(' ')
    time.sleep(0.3)
    pydirectinput.keyUp(' ')
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('d')
    time.sleep(0.4)
    pydirectinput.keyUp('d')
    pydirectinput.press('w')
    pydirectinput.press('w')
    pydirectinput.keyDown('d')
    time.sleep(0.7)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('s')
    time.sleep(1.3)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('d')
    time.sleep(1.1)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('w')
    time.sleep(1.8)
    pydirectinput.keyUp('w')
    pydirectinput.keyDown('d')
    time.sleep(2)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('w')
    pydirectinput.keyDown(' ')
    time.sleep(10.2)
    pydirectinput.keyUp('w')
    pydirectinput.keyUp(' ')
    pydirectinput.keyDown('a')
    time.sleep(2.5)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('w')
    time.sleep(0.3)
    pydirectinput.keyUp('w')
    pydirectinput.keyDown('a')
    time.sleep(1.9)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(0.9)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('a')
    time.sleep(5.5)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('w')
    time.sleep(1)
    pydirectinput.keyUp('w')
    pydirectinput.keyDown('a')
    time.sleep(1.5)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(1)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('a')
    time.sleep(1)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('w')
    time.sleep(1)
    pydirectinput.keyUp('w')
    pydirectinput.keyDown('a')
    time.sleep(1)
    pydirectinput.keyUp('a')
    time.sleep(1)
    pydirectinput.keyDown('s')
    pydirectinput.keyDown('d')
    time.sleep(1.5)
    pydirectinput.keyUp('s')
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('w')
    pydirectinput.keyDown('d')
    time.sleep(2)
    pydirectinput.keyUp('w')
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('s')
    pydirectinput.keyDown('d')
    time.sleep(2)
    pydirectinput.keyUp('s')
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('a')
    time.sleep(5)
    pydirectinput.press(' ')
    pydirectinput.keyDown('a')
    time.sleep(4.1)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(1.6)
    print('test')
    pydirectinput.keyUp('s')
    pydirectinput.keyDown(' ')
    pydirectinput.keyDown('s')
    time.sleep(1)
    pydirectinput.keyUp('s')
    pydirectinput.keyUp(' ')
    pydirectinput.keyDown('a')
    time.sleep(1)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(1)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('d')
    time.sleep(0.1)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('s')
    pydirectinput.keyDown(' ')
    time.sleep(0.4)

    pydirectinput.keyUp(' ')
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('s')
    pydirectinput.keyDown(' ')
    time.sleep(1.7)
    pydirectinput.keyUp(' ')
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('d')
    pydirectinput.keyDown(' ')
    time.sleep(2)
    pydirectinput.keyUp('d')
    pydirectinput.keyUp(' ')
    pydirectinput.press('s')
    pydirectinput.press('s')
    pydirectinput.keyDown('d')
    time.sleep(0.5)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown(' ')
    pydirectinput.keyDown('d')
    time.sleep(1.5)
    pydirectinput.keyUp('d')
    pydirectinput.keyUp(' ')

    pydirectinput.keyDown('d')
    pydirectinput.keyDown(' ')
    time.sleep(0.7)
    pydirectinput.keyUp('d')
    pydirectinput.keyUp(' ')

    pydirectinput.keyDown('s')
    time.sleep(2)
    pydirectinput.keyUp('s')
    pydirectinput.press('d')

    pydirectinput.keyDown('s')
    pydirectinput.keyDown(' ')
    time.sleep(4)
    pydirectinput.keyUp('s')
    pydirectinput.keyUp(' ')

    pydirectinput.keyDown('d')
    time.sleep(2)
    pydirectinput.keyUp('d')

    pydirectinput.keyDown('s')
    time.sleep(4)
    pydirectinput.keyUp('s')

    pydirectinput.press('/')
    pydirectinput.typewrite('/e dance')
    pydirectinput.press('enter')
    pydirectinput.press('/')
    pydirectinput.typewrite('ez')
    pydirectinput.press('enter')
    pydirectinput.keyDown('right')

    print("done")


if __name__ == "__main__":
    main()
